version: 2
jobs:
  test:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
        - checkout
        - run:
            name: install dependencies
            command: |
              sudo rm /var/lib/dpkg/lock
              python -m pip install pytest --no-cache-dir
              python -m pip install -r requirements.txt --no-cache-dir
        - run:
            name: run tests
            command: |
              python -m pytest test/test_main.py
  # build:
  #     machine:
  #       image: circleci/classic:201808-01
  #       docker_layer_caching: true
  #     working_directory: ~/repo
  #     steps:
  #       - checkout
  #       - run:
  #           name: build image
  #           command: |
  #             docker build -t $DOCKERHUB_USERNAME/rsvpapp:$CIRCLE_SHA1 .
  # push:
  #     machine:
  #       image: circleci/classic:201808-01
  #       docker_layer_caching: true
  #     working_directory: ~/repo
  #     steps:
  #       - checkout
  #       - run:
  #           name: Push image
  #           command: |
  #             docker build -t $DOCKERHUB_USERNAME/rsvpapp:$CIRCLE_SHA1 .
  #             echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USERNAME --password-stdin
  #             docker push $DOCKERHUB_USERNAME/rsvpapp:$CIRCLE_SHA1

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          context: DOCKERHUB
          filters:
            branches:
              only: dev
      # - build:
      #     context: DOCKERHUB
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: dev
      # - push:
      #     context: DOCKERHUB
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: dev